# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 139f95c6b745dad72e909ba69d474f1d9acf2f7c8b2cadcf02f8e227c4713b6edd8a2eea49b705781750f4d94dce77af1f774b131e1eb2a07f56f6fec6e39a19

test:
  secret_key_base: 547cc6aec1f6813450ddc0779bb5b80dcaec3d234653f5b9931fd0534e5a017ee9b6cec4d8770e082cb5c9bc3c2f621c7d5571e505c1ecc1eb9941fd8299c406

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
